# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mboiar/copter-gesture-control

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mboiar/copter-gesture-control

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mboiar/copter-gesture-control/CMakeFiles /home/mboiar/copter-gesture-control//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mboiar/copter-gesture-control/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named drone_gesture_controller

# Build rule for target.
drone_gesture_controller: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 drone_gesture_controller
.PHONY : drone_gesture_controller

# fast build rule for target.
drone_gesture_controller/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/build
.PHONY : drone_gesture_controller/fast

src/controller.o: src/controller.cpp.o
.PHONY : src/controller.o

# target to build an object file
src/controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/controller.cpp.o
.PHONY : src/controller.cpp.o

src/controller.i: src/controller.cpp.i
.PHONY : src/controller.i

# target to preprocess a source file
src/controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/controller.cpp.i
.PHONY : src/controller.cpp.i

src/controller.s: src/controller.cpp.s
.PHONY : src/controller.s

# target to generate assembly for a file
src/controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/controller.cpp.s
.PHONY : src/controller.cpp.s

src/drone.o: src/drone.cpp.o
.PHONY : src/drone.o

# target to build an object file
src/drone.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/drone.cpp.o
.PHONY : src/drone.cpp.o

src/drone.i: src/drone.cpp.i
.PHONY : src/drone.i

# target to preprocess a source file
src/drone.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/drone.cpp.i
.PHONY : src/drone.cpp.i

src/drone.s: src/drone.cpp.s
.PHONY : src/drone.s

# target to generate assembly for a file
src/drone.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/drone.cpp.s
.PHONY : src/drone.cpp.s

src/face_detection.o: src/face_detection.cpp.o
.PHONY : src/face_detection.o

# target to build an object file
src/face_detection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/face_detection.cpp.o
.PHONY : src/face_detection.cpp.o

src/face_detection.i: src/face_detection.cpp.i
.PHONY : src/face_detection.i

# target to preprocess a source file
src/face_detection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/face_detection.cpp.i
.PHONY : src/face_detection.cpp.i

src/face_detection.s: src/face_detection.cpp.s
.PHONY : src/face_detection.s

# target to generate assembly for a file
src/face_detection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/face_detection.cpp.s
.PHONY : src/face_detection.cpp.s

src/gesture_detection.o: src/gesture_detection.cpp.o
.PHONY : src/gesture_detection.o

# target to build an object file
src/gesture_detection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/gesture_detection.cpp.o
.PHONY : src/gesture_detection.cpp.o

src/gesture_detection.i: src/gesture_detection.cpp.i
.PHONY : src/gesture_detection.i

# target to preprocess a source file
src/gesture_detection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/gesture_detection.cpp.i
.PHONY : src/gesture_detection.cpp.i

src/gesture_detection.s: src/gesture_detection.cpp.s
.PHONY : src/gesture_detection.s

# target to generate assembly for a file
src/gesture_detection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/gesture_detection.cpp.s
.PHONY : src/gesture_detection.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... drone_gesture_controller"
	@echo "... src/controller.o"
	@echo "... src/controller.i"
	@echo "... src/controller.s"
	@echo "... src/drone.o"
	@echo "... src/drone.i"
	@echo "... src/drone.s"
	@echo "... src/face_detection.o"
	@echo "... src/face_detection.i"
	@echo "... src/face_detection.s"
	@echo "... src/gesture_detection.o"
	@echo "... src/gesture_detection.i"
	@echo "... src/gesture_detection.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

