# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mboiar/copter-gesture-control

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mboiar/copter-gesture-control

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mboiar/copter-gesture-control/CMakeFiles /home/mboiar/copter-gesture-control//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mboiar/copter-gesture-control/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named drone_gesture_controller

# Build rule for target.
drone_gesture_controller: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 drone_gesture_controller
.PHONY : drone_gesture_controller

# fast build rule for target.
drone_gesture_controller/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/build
.PHONY : drone_gesture_controller/fast

#=============================================================================
# Target rules for targets named copter_gesture_controller__test

# Build rule for target.
copter_gesture_controller__test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 copter_gesture_controller__test
.PHONY : copter_gesture_controller__test

# fast build rule for target.
copter_gesture_controller__test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/build
.PHONY : copter_gesture_controller__test/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/controller.o: src/controller.cpp.o
.PHONY : src/controller.o

# target to build an object file
src/controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/controller.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/src/controller.cpp.o
.PHONY : src/controller.cpp.o

src/controller.i: src/controller.cpp.i
.PHONY : src/controller.i

# target to preprocess a source file
src/controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/controller.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/src/controller.cpp.i
.PHONY : src/controller.cpp.i

src/controller.s: src/controller.cpp.s
.PHONY : src/controller.s

# target to generate assembly for a file
src/controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/controller.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/src/controller.cpp.s
.PHONY : src/controller.cpp.s

src/drone.o: src/drone.cpp.o
.PHONY : src/drone.o

# target to build an object file
src/drone.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/drone.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/src/drone.cpp.o
.PHONY : src/drone.cpp.o

src/drone.i: src/drone.cpp.i
.PHONY : src/drone.i

# target to preprocess a source file
src/drone.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/drone.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/src/drone.cpp.i
.PHONY : src/drone.cpp.i

src/drone.s: src/drone.cpp.s
.PHONY : src/drone.s

# target to generate assembly for a file
src/drone.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/drone.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/src/drone.cpp.s
.PHONY : src/drone.cpp.s

src/face_detection.o: src/face_detection.cpp.o
.PHONY : src/face_detection.o

# target to build an object file
src/face_detection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/face_detection.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/src/face_detection.cpp.o
.PHONY : src/face_detection.cpp.o

src/face_detection.i: src/face_detection.cpp.i
.PHONY : src/face_detection.i

# target to preprocess a source file
src/face_detection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/face_detection.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/src/face_detection.cpp.i
.PHONY : src/face_detection.cpp.i

src/face_detection.s: src/face_detection.cpp.s
.PHONY : src/face_detection.s

# target to generate assembly for a file
src/face_detection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/face_detection.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/src/face_detection.cpp.s
.PHONY : src/face_detection.cpp.s

src/gesture_detection.o: src/gesture_detection.cpp.o
.PHONY : src/gesture_detection.o

# target to build an object file
src/gesture_detection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/gesture_detection.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/src/gesture_detection.cpp.o
.PHONY : src/gesture_detection.cpp.o

src/gesture_detection.i: src/gesture_detection.cpp.i
.PHONY : src/gesture_detection.i

# target to preprocess a source file
src/gesture_detection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/gesture_detection.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/src/gesture_detection.cpp.i
.PHONY : src/gesture_detection.cpp.i

src/gesture_detection.s: src/gesture_detection.cpp.s
.PHONY : src/gesture_detection.s

# target to generate assembly for a file
src/gesture_detection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/gesture_detection.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/src/gesture_detection.cpp.s
.PHONY : src/gesture_detection.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_gesture_controller.dir/build.make CMakeFiles/drone_gesture_controller.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

test/main_gtest.o: test/main_gtest.cpp.o
.PHONY : test/main_gtest.o

# target to build an object file
test/main_gtest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/test/main_gtest.cpp.o
.PHONY : test/main_gtest.cpp.o

test/main_gtest.i: test/main_gtest.cpp.i
.PHONY : test/main_gtest.i

# target to preprocess a source file
test/main_gtest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/test/main_gtest.cpp.i
.PHONY : test/main_gtest.cpp.i

test/main_gtest.s: test/main_gtest.cpp.s
.PHONY : test/main_gtest.s

# target to generate assembly for a file
test/main_gtest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/test/main_gtest.cpp.s
.PHONY : test/main_gtest.cpp.s

test/test_face_detection.o: test/test_face_detection.cpp.o
.PHONY : test/test_face_detection.o

# target to build an object file
test/test_face_detection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/test/test_face_detection.cpp.o
.PHONY : test/test_face_detection.cpp.o

test/test_face_detection.i: test/test_face_detection.cpp.i
.PHONY : test/test_face_detection.i

# target to preprocess a source file
test/test_face_detection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/test/test_face_detection.cpp.i
.PHONY : test/test_face_detection.cpp.i

test/test_face_detection.s: test/test_face_detection.cpp.s
.PHONY : test/test_face_detection.s

# target to generate assembly for a file
test/test_face_detection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/test/test_face_detection.cpp.s
.PHONY : test/test_face_detection.cpp.s

test/test_gesture_detection.o: test/test_gesture_detection.cpp.o
.PHONY : test/test_gesture_detection.o

# target to build an object file
test/test_gesture_detection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/test/test_gesture_detection.cpp.o
.PHONY : test/test_gesture_detection.cpp.o

test/test_gesture_detection.i: test/test_gesture_detection.cpp.i
.PHONY : test/test_gesture_detection.i

# target to preprocess a source file
test/test_gesture_detection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/test/test_gesture_detection.cpp.i
.PHONY : test/test_gesture_detection.cpp.i

test/test_gesture_detection.s: test/test_gesture_detection.cpp.s
.PHONY : test/test_gesture_detection.s

# target to generate assembly for a file
test/test_gesture_detection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copter_gesture_controller__test.dir/build.make CMakeFiles/copter_gesture_controller__test.dir/test/test_gesture_detection.cpp.s
.PHONY : test/test_gesture_detection.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... copter_gesture_controller__test"
	@echo "... drone_gesture_controller"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... src/controller.o"
	@echo "... src/controller.i"
	@echo "... src/controller.s"
	@echo "... src/drone.o"
	@echo "... src/drone.i"
	@echo "... src/drone.s"
	@echo "... src/face_detection.o"
	@echo "... src/face_detection.i"
	@echo "... src/face_detection.s"
	@echo "... src/gesture_detection.o"
	@echo "... src/gesture_detection.i"
	@echo "... src/gesture_detection.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... test/main_gtest.o"
	@echo "... test/main_gtest.i"
	@echo "... test/main_gtest.s"
	@echo "... test/test_face_detection.o"
	@echo "... test/test_face_detection.i"
	@echo "... test/test_face_detection.s"
	@echo "... test/test_gesture_detection.o"
	@echo "... test/test_gesture_detection.i"
	@echo "... test/test_gesture_detection.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

